package com.xiao.dao;

import com.xiao.po.ReaderCard;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("readerDao")
public interface ReaderCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Fri Jun 26 20:50:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Fri Jun 26 20:50:53 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Fri Jun 26 20:50:53 CST 2020
     */
    int insertSelective(ReaderCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Fri Jun 26 20:50:53 CST 2020
     */
    ReaderCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Fri Jun 26 20:50:53 CST 2020
     */
    int updateByPrimaryKeySelective(ReaderCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Fri Jun 26 20:50:53 CST 2020
     */
    int updateByPrimaryKey(ReaderCard record);

    /**
     * 查询所有的记录信息
     */
    List<ReaderCard> queryReaderListAll(ReaderCard readerCard);

    /**
     * 根据用户名和密码判断用户是否存在
     */
    ReaderCard queryUserInfoByNameAndPassword(@Param("username") String username, @Param("password")String password);
}